In [1]:
import numpy as np
import pandas as pd
from src.utils import get_all_paths

In [2]:
weights_paths = get_all_paths("/Users/saru/Local_Work/neuromodul/fscv/tests_code/data_1d_vxlbl")
voltammograms_path = "/Users/saru/Local_Work/neuromodul/fscv/tests_code/data_1d_vxlbl/AFOR/bfa/155Vs/10Hz/2025_07_07__AFOR__DA_5HT_NE__155Vs_10Hz__BFA_INM001_99bW06R09/DA_5HT_NE/voltammograms.npy"
labels_path = "/Users/saru/Local_Work/neuromodul/fscv/tests_code/data_1d_vxlbl/AFOR/bfa/155Vs/10Hz/2025_07_07__AFOR__DA_5HT_NE__155Vs_10Hz__BFA_INM001_99bW06R09/DA_5HT_NE/labels.npy"


In [3]:
from src.utils import load_activation_data
train, val, test = load_activation_data(weights_paths, batch_size=32)


[[   0.    0.    0.]
 [   0.    0.  500.]
 [   0.    0. 1000.]
 [   0.    0. 1500.]
 [   0.  500.    0.]
 [   0.  500.  500.]
 [   0.  840.  840.]
 [   0.  840. 1680.]
 [   0. 1000.    0.]
 [   0. 1500.    0.]
 [  90.    0.    0.]
 [ 180.    0.    0.]
 [ 270.    0.    0.]
 [ 360.    0.    0.]
 [ 450.    0.    0.]
 [ 500.    0.    0.]
 [ 500.    0.  500.]
 [ 500.  500.    0.]
 [ 500.  500.  500.]
 [ 540.    0.    0.]
 [ 630.    0.    0.]
 [ 720.    0.    0.]
 [ 810.    0.    0.]
 [ 840.  840.  840.]
 [ 840. 1680.  840.]
 [ 840. 1680. 1680.]
 [ 900.    0.    0.]
 [ 990.    0.    0.]
 [1000.    0.    0.]
 [1000.  500. 1000.]
 [1080.    0.    0.]
 [1170.    0.    0.]
 [1260.    0.    0.]
 [1350.    0.    0.]
 [1440.    0.    0.]
 [1500.    0.    0.]
 [1530.    0.    0.]
 [1620.    0.    0.]
 [1710.    0.    0.]
 [1800.    0.    0.]
 [1890.    0.    0.]
 [1980.    0.    0.]
 [2070.    0.    0.]
 [2160.    0.    0.]
 [2250.    0.    0.]
 [2340.    0.    0.]
 [2430.    0.    0.]
 [2520.    0.

In [4]:
from src.reg_models import Regressor, train_regressor, test_regressor
from torch.optim import Adam
from torch import nn

In [5]:
model = Regressor(80,3)
optim = Adam(model.parameters(), lr=1e-3)
loss = nn.MSELoss()

In [6]:
train_loss = train_regressor(model=model,train_data_loader=train, val_loader=val,loss=loss,optimizer=optim, device="mps", num_epochs=50)

Epoch 5/50| Train Loss: 0.7966| Val Loss: 0.9800
Epoch 10/50| Train Loss: 0.7794| Val Loss: 0.9845
Epoch 15/50| Train Loss: 0.7708| Val Loss: 0.9986
Epoch 20/50| Train Loss: 0.7623| Val Loss: 1.0139
Epoch 25/50| Train Loss: 0.7553| Val Loss: 0.9865
Epoch 30/50| Train Loss: 0.7522| Val Loss: 0.9803
Epoch 35/50| Train Loss: 0.7479| Val Loss: 1.0062
Epoch 40/50| Train Loss: 0.7473| Val Loss: 1.0205
Epoch 45/50| Train Loss: 0.7412| Val Loss: 1.0067
Epoch 50/50| Train Loss: 0.7356| Val Loss: 1.0558
